[project]
name = "ray-examples"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ray[data]>=2.46.0",
    "vllm==0.7.2",
]
